"""Report templates shared by the synthetic study and real-data runs.

THE REPORT CONTRACT. A generated report is instrument output: it states
what was fit, on what data, under what scheme, with what results, in prose
that holds word-for-word on a stranger's dataset. Three kinds of content
are allowed. (1) Template prose: fixed sentences plus injected values, each
technical term defined inline exactly once, in one place in this module.
(2) Presence-keyed measurement blocks, wrapped in pk-comment markers and
rendered only when the metrics carry the measurement (the generator block,
the oracle and Sharpe columns, the within-group decomposition, the seed-8
file); never a mode flag. (3) Notes: authored markdown per run (notes.py),
inserted at fixed anchors, carrying all interpretation, motivation, and
dataset-specific claims, citing metric values through @val tokens that fail
the build when unresolvable. Anything editorial belongs in a run's notes,
not here. The template-invariance and word-budget tests enforce (1) and
(2); render-time numbering and the cited-or-fail figure rule live in
document.ReportDoc.
"""

from __future__ import annotations

from pathlib import Path

from .document import (
    ReportDoc as ReportDoc,
)
from .document import (
    emit_pdf as emit_pdf,
)
from .document import (
    img_uri,
    pct,
)
from .notes import load_run_notes
from .units import horizon_label, unit_abbrev, unit_singular


def _pk(name: str, html: str) -> str:
    """Wrap a presence-keyed block in markers the invariance test strips by
    whitelist. A block that renders in one variant and not the other without
    these markers is a template divergence and fails that test."""
    return f"<!--pk:{name}-->{html}<!--/pk:{name}-->"


def synthetic_context(
    m: dict, m8: dict | None, reports_dir: Path, notes_dir: Path | None = None
) -> dict:
    g, d, folds = m["generator"], m["dataset"], m["folds"]

    meta_rows = f"""    <tr><th>Author</th><td>Robert Stevenson</td></tr>
    <tr><th>Repository</th><td>survival-analysis-pipeline</td></tr>
    <tr><th>Run</th><td>seed {g["seed"]}, {d["n_strategies"]:,} strategies,
      {len(folds)} temporal folds</td></tr>
    <tr><th>Source of figures</th><td>reports/metrics.json, regenerated by
      <code>python scripts/run_synthetic_pipeline.py</code></td></tr>"""

    footer = f"""<p>Generated from <code>reports/metrics.json</code> by
<code>scripts/run_build_report.py</code>. Seed {g["seed"]},
{d["n_strategies"]:,} strategies, {m["pooled"]["n_test"]:,} out-of-fold test
strategies.</p>"""

    command = (
        "pip install -r requirements.txt\n"
        "python -m pytest\n"
        "python scripts/run_synthetic_pipeline.py"
    )

    return {
        "m": m,
        "m8": m8,
        "figures_dir": reports_dir / "figures",
        "title": "Predicting the Working Life of Algorithmically Discovered Trading Strategies",
        "subtitle": "A survival-analysis study, built and verified against\n"
        "  synthetic ground truth",
        "meta_rows": meta_rows,
        "footer": footer,
        "command": command,
        "source_desc": f"synthetic data drawn at seed {g['seed']}",
        "km": None,
        "notes": load_run_notes(notes_dir, m),
    }


def real_context(m: dict, run_dir: Path, notes_dir: Path | None = None) -> dict:
    run, d, pool = m["run"], m["dataset"], m["pooled"]

    # One line on purpose. A cmd.exe caret continuation is a parse error in
    # PowerShell and a stray argument in bash, so a wrapped command is a
    # command the reader cannot paste. --out is included because without it
    # the run lands in the default runs/<name>/ and the rebuild step below
    # would re-render the old report instead of the one just produced.
    cols = run["columns"]
    drop_part = f" --drop-cols {','.join(cols['dropped'])}" if cols["dropped"] else ""
    categorical = cols.get("categorical")
    cat_part = f" --categorical-cols {','.join(categorical)}" if categorical else ""
    km_part = f" --km-col {run['km_col']}" if run.get("km_col") else ""
    out_part = f" --out {run['out_dir']}" if run.get("out_dir") else ""
    # Days is the CLI default, so day-based commands stay exactly as the
    # committed reports print them.
    run_unit = run.get("time_unit", "days")
    unit_part = f" --time-unit {run_unit}" if run_unit != "days" else ""
    command = (
        f"python scripts/run_fit_evaluate.py --data {run['source']} --name {run['name']} "
        f"--id-col {cols['id']} --date-col {cols['date']} "
        f"--duration-col {cols['duration']} --event-col {cols['event']}"
        f"{drop_part}{cat_part}{km_part}{unit_part} --folds {run['n_folds']} "
        f"--horizons {','.join(horizon_label(h) for h in run['horizons_days'])}{out_part}"
        f"\npython scripts/run_build_report.py --run {run_dir.as_posix()}"
    )

    censored_overall = 1.0 - d["event_rate"]
    meta_rows = f"""    <tr><th>Source data</th><td><code>{run["source"]}</code></td></tr>
    <tr><th>Rows</th><td>{d["n_rows"]:,} ({pct(d["event_rate"])} with the ending
      observed, {pct(censored_overall)} censored)</td></tr>
    <tr><th>Start dates</th><td>{d["date_min"]} to {d["date_max"]}</td></tr>
    <tr><th>Evaluation</th><td>{run["n_folds"]} expanding-window temporal folds</td></tr>
    <tr><th>Source of figures</th><td><code>{run_dir.as_posix()}/metrics.json</code>,
      regenerated by the command in section @sec:repro</td></tr>"""

    footer = f"""<p>Generated from <code>{run_dir.as_posix()}/metrics.json</code> by
<code>scripts/run_build_report.py --run</code>. {d["n_rows"]:,} rows,
{pool["n_test"]:,} out-of-time test rows.</p>"""

    km = None
    km_col = run.get("km_col")
    if km_col and (run_dir / "figures" / "km_by_group.png").exists():
        km = {"col": km_col, "filename": "km_by_group.png"}

    if notes_dir is None:
        notes_dir = run_dir / "notes"

    return {
        "m": m,
        "m8": None,
        "figures_dir": run_dir / "figures",
        "title": f"Survival Model Evaluation: {run['name']}",
        "subtitle": "Fitted with the survival-analysis-pipeline;\n"
        "  methodology validated separately against synthetic ground truth",
        "meta_rows": meta_rows,
        "footer": footer,
        "command": command,
        "source_desc": f"<code>{Path(run['source']).name}</code>",
        "km": km,
        "notes": load_run_notes(notes_dir, m),
    }


def seed_dependence_para(m: dict, m8: dict | None) -> str:
    """Seed-dependence values, computed from the seed-8 metrics when they
    exist so the claim is measured, not asserted."""
    p, pool, shap = m["params"], m["pooled"], m["shap_top"]
    if m8 is None:
        return (
            "<p>All results come from one generator seed. No second-seed run is on "
            "file, so data variance and model variance cannot be separated.</p>"
        )
    p8, pool8, shap8 = m8["params"], m8["pooled"], m8["shap_top"]
    same_params = p8["max_depth"] == p["max_depth"] and p8["aft_sigma"] == p["aft_sigma"]
    in_ci = pool["c_xgb_ci"][0] <= pool8["c_xgb"] <= pool["c_xgb_ci"][1]
    top3_same = {s["feature"] for s in shap[:3]} == {s["feature"] for s in shap8[:3]}
    order_same = [s["feature"] for s in shap[:3]] == [s["feature"] for s in shap8[:3]]
    # An order claim needs a margin that survives platform noise. requirements.txt
    # records cross-platform attribution drift near 1e-3; below twice that, a
    # matching order is a coincidence of decimals, not a confirmation.
    order_margin = min(shap8[i]["mean_abs_shap"] - shap8[i + 1]["mean_abs_shap"] for i in range(2))
    if top3_same and order_same and order_margin >= 0.002:
        attribution = "The top three attribution features match, in the same order."
    elif top3_same and order_same:
        attribution = (
            "The top three attribution features match; their order matches as well, "
            "but the closest pair sits inside the cross-platform attribution drift "
            "recorded in requirements.txt, so the matching order is a tie rather "
            "than a confirmation."
        )
    elif top3_same:
        attribution = "The top three attribution features match; their internal order shifts."
    else:
        attribution = "The set of dominant attribution features shifted between seeds."
    seed_a = (m.get("generator") or {}).get("seed")
    seed_b = (m8.get("generator") or {}).get("seed")
    run_b = f"seed {seed_b}" if seed_b is not None else "a second seed"
    owner_a = f"seed-{seed_a} " if seed_a is not None else "first run's "
    return (
        f"<p>A second-seed run ({run_b}, <code>reports/metrics_seed8.json</code>) "
        f"selected {'the same' if same_params else 'different'} hyperparameters and "
        f"scored {pool8['c_xgb']:.3f}, {'inside' if in_ci else 'outside'} the "
        f"{owner_a}interval of {pool['c_xgb_ci'][0]:.3f} to "
        f"{pool['c_xgb_ci'][1]:.3f}; Sharpe ranked {pool8['c_sharpe']:.3f}, the oracle "
        f"ranking {pool8['c_oracle']:.3f}. " + attribution + " Two seeds is a "
        "consistency check, not a variance estimate.</p>"
    )


# --------------------------------------------------------------------------
# Derived rendering state shared by the section builders.


def _derive(ctx: dict) -> dict:
    m = ctx["m"]
    d, pool, folds, cfg = m["dataset"], m["pooled"], m["folds"], m["config"]
    g, run = m.get("generator"), m.get("run")
    tu = cfg.get("time_unit", "days")
    hs = horizon_label(cfg["calibration_horizon_days"])
    tua = unit_abbrev(tu)
    fm_x, fm_c = pool["c_xgb_by_fold_mean"], pool["c_cox_by_fold_mean"]
    if f"{fm_x:.3f}" == f"{fm_c:.3f}":
        winner_clause = "the two models tie at the printed precision"
    elif fm_c > fm_x:
        winner_clause = "the Cox baseline scores higher"
    else:
        winner_clause = "the boosted model scores higher"
    # Whether pooled reads low is a property of the run, not of the method,
    # so the sentence is computed rather than asserted (the synthetic run's
    # pooled figure sits a hair above its fold mean).
    if f"{pool['c_xgb']:.3f}" == f"{fm_x:.3f}":
        pooled_clause = "on this run it matches the fold mean at the printed precision"
    elif pool["c_xgb"] < fm_x:
        pooled_clause = "on this run it reads conservative next to the fold mean"
    else:
        pooled_clause = "on this run it reads slightly high next to the fold mean"
    return {
        "m": m,
        "m8": ctx["m8"],
        "notes": ctx.get("notes") or {},
        "figures_dir": ctx["figures_dir"],
        "source_desc": ctx["source_desc"],
        "command": ctx["command"],
        "km": ctx["km"],
        "g": g,
        "run": run,
        "p": m["params"],
        "d": d,
        "pool": pool,
        "folds": folds,
        "brier": m["ipcw_brier"],
        "shap": m["shap_top"],
        "cfg": cfg,
        "wg": m.get("within_group"),
        "tu": tu,
        "tu1": unit_singular(tu),
        "tua": tua,
        "hs": hs,
        "cal": m[f"calibration_{hs}{tua}"],
        "has_oracle": "c_oracle" in pool,
        "has_sharpe": "c_sharpe" in pool,
        "unit": "strategy" if g else "row",
        "units": "strategies" if g else "rows",
        "n_rows": d.get("n_rows") or d.get("n_strategies"),
        "date_min": d.get("date_min") or (g or {}).get("discovery_start"),
        "date_max": d.get("date_max") or (g or {}).get("observation_cutoff"),
        "censored_overall": 1.0 - d["event_rate"],
        "last_fold_censored": 1.0 - folds[-1]["test_event_rate"],
        "c_fold_min": min(f["c_xgb"] for f in folds),
        "c_fold_max": max(f["c_xgb"] for f in folds),
        "n_train_min": min(f["n_train"] for f in folds),
        "n_train_max": max(f["n_train"] for f in folds),
        "winner_clause": winner_clause,
        "pooled_clause": pooled_clause,
    }


def _sec_summary(c: dict, doc: ReportDoc) -> None:
    pool, folds = c["pool"], c["folds"]
    body = f"""<p>This report evaluates two survival models fitted to {c["source_desc"]}.
It holds {c["n_rows"]:,} {c["units"]}, each observed from its start
date. {pct(c["d"]["event_rate"])} have observed endings and
{pct(c["censored_overall"])} are censored, still running when observation
stopped. Median observed duration is
{c["d"]["median_observed_duration_days"]:.0f} {c["tu"]}. The models predict,
from what was on file at the start date, how long each {c["unit"]}
survives.</p>

<p>The like-for-like comparison is the fold mean. Each of the {len(folds)}
temporal folds fits both models on its own window, and the fold scores
average. On concordance, the share of pairs a ranking orders correctly
where 0.500 is a coin flip, XGBoost AFT scores
{pool["c_xgb_by_fold_mean"]:.3f} and the Cox proportional hazards baseline
{pool["c_cox_by_fold_mean"]:.3f}; {c["winner_clause"]}.</p>

<p>Pooled over {pool["n_test"]:,} out-of-time test {c["units"]}, the AFT
model scores {pool["c_xgb"]:.3f} (95% bootstrap interval
{pool["c_xgb_ci"][0]:.3f} to {pool["c_xgb_ci"][1]:.3f}); section
@sec:results explains how the two figures differ.</p>"""
    if c["run"]:
        body += "\n" + _pk(
            "bundle",
            "<p>Both fitted models are saved; the bundle records the recommended"
            " model for scoring new rows.</p>",
        )
    if c["wg"]:
        wg = c["wg"]
        # Whether group membership dominates is a property of the run, so the
        # lead-in is computed, not asserted (same rule as pooled_clause).
        if wg["c_group_mean"] >= pool["c_xgb"]:
            wg_lead = (
                f"Most of the pooled figure reflects a {c['unit']}'s <code>{wg['col']}</code> group"
            )
        else:
            wg_lead = (
                f"The pooled figure splits between <code>{wg['col']}</code>"
                " group membership and ranking within it"
            )
        body += "\n" + _pk(
            "within-group",
            f"""<p>{wg_lead}: group means alone score
{wg["c_group_mean"]:.3f}, within-group comparisons {wg["c_within"]:.3f};
section @sec:results gives the decomposition.</p>""",
        )
    if c["g"] and c["has_oracle"] and c["has_sharpe"]:
        body += "\n" + _pk(
            "oracle-summary",
            f"""<p>An oracle ranking (Addendum A) bounds every model at
{pool["c_oracle"]:.3f}; ranking by validation Sharpe scores
{pool["c_sharpe"]:.3f}, below the coin flip in every fold (mechanism in
the notes).</p>""",
        )
    if c["g"]:
        body += "\n" + _pk(
            "synthetic-callout",
            '<p class="callout">All results are synthetic; the run validates the'
            " pipeline and asserts nothing about live data.</p>",
        )
    else:
        body += "\n" + _pk(
            "no-oracle-callout",
            '<p class="callout">This dataset has no known generating process, so'
            " no oracle ceiling bounds these scores, and feature attributions"
            " cannot be checked against a true mechanism.</p>",
        )
    doc.section("summary", "Summary", body)


def _sec_data(c: dict, doc: ReportDoc) -> None:
    cols = (c["run"] or {}).get("columns")
    extra_cols = ""
    if cols and cols.get("dropped"):
        extra_cols += f" Columns dropped before fitting: {', '.join(cols['dropped'])}."
    if cols and cols.get("categorical"):
        extra_cols += (
            " These columns hold numeric codes rather than quantities and were"
            f" forced to categorical: {', '.join(cols['categorical'])}."
        )
    if extra_cols:
        extra_cols = _pk("columns", extra_cols)
    body = f"""<p>Start dates run {c["date_min"]} to {c["date_max"]}; durations are
measured in {c["tu"]}.{extra_cols}</p>

<p>The pipeline treats every {c["unit"]} as observed from its own start
date. It has no support for left truncation, {c["units"]} whose life began
before the source window, which must be excluded during preparation;
whether they were is recorded with the dataset.</p>"""
    if c["g"]:
        g = c["g"]
        body += "\n" + _pk(
            "generator-data",
            f"""<p>{pct(g["admin_censor_rate"], 0)} of {c["units"]} are
administratively retired independent of performance, and survival time is
log-normal in the latents at scale {g["log_time_sigma"]}.</p>""",
        )
    if c["notes"].get("data"):
        body += "\n\n" + c["notes"]["data"]
    if c["km"]:
        km_col = c["km"]["col"]
        km_caption = (
            f"Kaplan-Meier survival curves by <code>{km_col}</code>. Groups"
            " beyond the seven most frequent are collapsed into (other) for"
            " this plot only."
        )
        if c["notes"].get("km_caption"):
            km_caption += " " + c["notes"]["km_caption"]
        km_fig = doc.figure(
            "km",
            img_uri(c["figures_dir"], c["km"]["filename"]),
            f"Kaplan-Meier survival curves by {km_col}",
            km_caption,
        )
        body += "\n" + _pk(
            "km-figure",
            f"""<p>Figure @fig:km shows Kaplan-Meier survival curves by
<code>{km_col}</code>, the coarsest structure in the outcome before any
model is fitted (estimator defined in section @sec:results).</p>

{km_fig}""",
        )
    doc.section("data", "Data", body)


def _sec_method(c: dict, doc: ReportDoc) -> None:
    p, cfg, folds = c["p"], c["cfg"], c["folds"]
    body = f"""<h3>@sec:method.1 Model class</h3>

<p>The target is a duration with incomplete observations, so the model is an
accelerated failure time (AFT) model, XGBoost with its
<code>survival:aft</code> objective. An observed ending enters as [t, t]
and a censored {c["unit"]} as [t, infinity), so every {c["unit"]}
contributes. The model predicts each {c["unit"]}'s median
survival time in {c["tu"]}, and a log-normal curve of fitted, shared width
around that median gives the probability of surviving any horizon. A Cox
proportional hazards baseline, the standard linear survival model, is
fitted with lifelines' <code>CoxPHFitter</code> on the same features and
answers whether the boosted model was necessary.</p>

<p>Numeric features pass through, missing values included (the Cox baseline
gets train-window median imputation); text columns are one-hot encoded with
the vocabulary refit per training window, so a fold's features reflect only
what was on file by its split date.</p>

<h3>@sec:method.2 Temporal validation and label re-censoring</h3>

<p>Evaluation uses {len(folds)} expanding-window folds ordered by start
date: the earliest {pct(cfg["min_train_frac"], 0)} of {c["units"]} is
burn-in, and each fold trains on every {c["unit"]} started before its split
date and tests on the next block (sizes in Table @tab:folds).</p>

<p>Training labels are re-censored at each split date. A {c["unit"]}
started long before a split may have died after it, and its label
contains that future, so every post-split death is rewritten as a censoring
at the split. Omitting this raises scores by importing the future, which
makes it the most consequential detail in the pipeline; it is a standalone
function (<code>cv.recensor</code>) with dedicated tests.</p>

<h3>@sec:method.3 Selection and calibration</h3>

<p>Hyperparameters are selected once, on the first fold's training window,
by an inner temporal split scored on held-out censored log-likelihood;
concordance is scale-invariant and cannot see an unusable distribution
width. The predictive scale, the reported curves' width, is calibrated on a
temporal tail slice by a probe model that never trained on those rows; the
selected loss scale was {p["aft_sigma"]}, the calibrated predictive scale
{p["predictive_sigma_final"]:.2f}.</p>"""
    if c["run"]:
        body += "\n" + _pk(
            "validated-elsewhere",
            "<p>The methodology is validated separately against synthetic data"
            " with known ground truth; the repository's synthetic report"
            " documents those checks.</p>",
        )
    doc.section("method", "Method", body)


def _sec_results(c: dict, doc: ReportDoc) -> None:
    pool, folds, cfg, brier, cal = c["pool"], c["folds"], c["cfg"], c["brier"], c["cal"]
    conc_rows = ""
    if c["has_oracle"]:
        conc_rows += _pk(
            "oracle-row",
            f"""    <tr><td>Oracle ranking on latent log-time (ceiling)</td>
      <td>{pool["c_oracle"]:.3f}</td><td>not resampled</td></tr>""",
        )
    conc_rows += f"""
    <tr class="highlight"><td>XGBoost AFT (pooled)</td><td>{pool["c_xgb"]:.3f}</td>
      <td>{pool["c_xgb_ci"][0]:.3f} to {pool["c_xgb_ci"][1]:.3f}</td></tr>
    <tr><td>XGBoost AFT (fold mean)</td>
      <td>{pool["c_xgb_by_fold_mean"]:.3f}</td><td>not resampled</td></tr>
    <tr><td>Cox proportional hazards (fold mean)</td>
      <td>{pool["c_cox_by_fold_mean"]:.3f}</td><td>not resampled</td></tr>"""
    if c["has_sharpe"]:
        conc_rows += _pk(
            "sharpe-row",
            f"""
    <tr><td>Rank by validation Sharpe</td><td>{pool["c_sharpe"]:.3f}</td>
      <td>{pool["c_sharpe_ci"][0]:.3f} to {pool["c_sharpe_ci"][1]:.3f}</td></tr>""",
        )
    tab_conc = doc.table(
        "concordance",
        f"Concordance index by model, pooled over {pool['n_test']:,} test"
        f" {c['units']} with 95% percentile bootstrap intervals over"
        f" {cfg['n_bootstrap']} resamples. Higher is better; 0.500 is a coin"
        f" flip. Fold-mean rows score each of the {cfg['n_folds']} folds"
        " separately and average. The interval resamples test rows with the"
        " fitted models held fixed, so it measures scoring precision, not"
        " stability across history; the fold spread is the guide to that.",
        "<tr><th>Method</th><th>Concordance (Harrell's C)</th><th>95% interval</th></tr>",
        conc_rows,
    )

    worst = min(folds, key=lambda f: f["c_xgb"])
    worst_idx = folds.index(worst) + 1
    worst_sentence = c["notes"].get("worst_fold", "No cause is established for it in this report.")

    fold_head = (
        "<tr><th>Fold</th><th>Split date</th><th>Train n</th><th>Test n</th>\n"
        "    <th>Censored</th><th>AFT</th><th>Cox</th>"
    )
    if c["has_oracle"] and c["has_sharpe"]:
        fold_head += "<th>Sharpe</th><th>Oracle</th>"
    fold_head += "</tr>"
    fold_rows = []
    for i, f in enumerate(folds):
        row = (
            f"<tr><td>{i + 1}</td><td>{f['split_date']}</td><td>{f['n_train']:,}</td>"
            f"<td>{f['n_test']:,}</td><td>{pct(1 - f['test_event_rate'], 0)}</td>"
            f"<td>{f['c_xgb']:.3f}</td><td>{f['c_cox']:.3f}</td>"
        )
        if c["has_oracle"] and c["has_sharpe"]:
            row += f"<td>{f['c_sharpe']:.3f}</td><td>{f['c_oracle']:.3f}</td>"
        fold_rows.append(row + "</tr>")
    tab_folds = doc.table(
        "folds",
        "Per-fold results. Censoring is the share of each fold's test"
        f" {c['units']} whose ending was not observed.",
        fold_head,
        "\n".join(fold_rows),
    )
    fig_folds = doc.figure(
        "fold-cindex",
        img_uri(c["figures_dir"], "fold_cindex.png"),
        "Concordance index by temporal fold",
        f"Concordance by fold, from {c['c_fold_min']:.3f} to"
        f" {c['c_fold_max']:.3f}. Folds differ in censoring mix, so cross-fold"
        " comparisons are indicative rather than exact.",
    )

    body = f"""<h3>@sec:results.1 Discrimination</h3>

{tab_conc}

<p>Each fold refits both models on its own window, and the Cox risk scores
are relative to that window, so fold-mean rows are the like-for-like
comparison. The pooled row concatenates {len(folds)} separately fitted AFT
models whose levels can differ, blurring cross-fold pairs;
{c["pooled_clause"]}.</p>

<p>The weakest window is fold {worst_idx}, starting {worst["split_date"]},
at {worst["c_xgb"]:.3f}. {worst_sentence}</p>"""
    if c["wg"]:
        wg = c["wg"]
        body += "\n" + _pk(
            "within-group-results",
            f"""<p>The pooled concordance decomposes by <code>{wg["col"]}</code>:
group means alone score {wg["c_group_mean"]:.3f}, and comparisons
restricted to same-group {c["units"]} score {wg["c_within"]:.3f}
(pair-weighted across {wg["n_groups"]} qualifying groups). The
within-group distance above 0.500 is {c["unit"]}-level skill; the rest is
group membership.</p>""",
        )
    if c["has_sharpe"]:
        smin = min(f["c_sharpe"] for f in folds)
        smax = max(f["c_sharpe"] for f in folds)
        flip = pool.get("c_sharpe_flipped")
        flip_sentence = (
            f" Reversed, it scores {flip:.3f}, its arithmetic complement, short"
            f" of the model's {pool['c_xgb']:.3f}."
            if flip is not None
            else ""
        )
        body += "\n" + _pk(
            "sharpe-results",
            f"""<p>Validation-Sharpe ranking scores {pool["c_sharpe"]:.3f} pooled,
{smin:.3f} to {smax:.3f} across folds, never above 0.500.{flip_sentence}</p>""",
        )
    body += f"""

<p>Figure @fig:fold-cindex plots Table @tab:folds' per-fold
concordance.</p>

{tab_folds}

{fig_folds}

<h3>@sec:results.2 Calibration</h3>

<p>The Brier score, the mean squared error of a probability forecast
(lower is better), is weighted by the inverse probability of censoring
(IPCW) so censored {c["units"]} do not bias it; the no-skill reference
assigns every {c["unit"]} the population's Kaplan-Meier marginal, the
fraction surviving at each age with censored {c["units"]} counted while
observed.</p>"""
    brier_rows = "\n".join(
        f"<tr><td>{h.removesuffix(c['tua'])} {c['tu']}</td><td>{v['xgb']:.3f}</td>"
        f"<td>{v['cox']:.3f}</td><td>{v['km_marginal']:.3f}</td></tr>"
        for h, v in brier.items()
    )
    tab_brier = doc.table(
        "brier",
        "IPCW Brier score by horizon. Lower is better.",
        "<tr><th>Horizon</th><th>AFT</th><th>Cox</th>\n    <th>No-skill marginal</th></tr>",
        brier_rows,
    )
    gaps = [(abs(b["predicted"] - b["observed_km"]), i) for i, b in enumerate(cal)]
    worst_gap, worst_bin = max(gaps)
    fig_cal = doc.figure(
        "calibration",
        img_uri(c["figures_dir"], f"calibration_{c['hs']}{c['tua']}.png"),
        f"Decile calibration at {c['hs']} {c['tu']}",
        f"Predicted against observed survival at {c['hs']} {c['tu']}, by"
        " predicted decile. Observed frequencies are Kaplan-Meier estimates"
        f" within each bin, so censored {c['units']} contribute correctly. The"
        f" largest deviation is {worst_gap:.3f} in decile {worst_bin + 1}.",
    )
    cal_rows = "\n".join(
        f"<tr><td>{i + 1}</td><td>{b['n']}</td><td>{b['predicted']:.3f}</td>"
        f"<td>{b['observed_km']:.3f}</td>"
        f"<td>{b['observed_km'] - b['predicted']:+.3f}</td></tr>"
        for i, b in enumerate(cal)
    )
    tab_cal = doc.table(
        "calibration",
        f"Decile calibration at {c['hs']} {c['tu']}, the values plotted in"
        " Figure @fig:calibration. The observed value in each decile is a"
        f" Kaplan-Meier estimate; when a decile's last observed {c['unit']}"
        f" falls short of the {c['hs']}-{c['tu1']} horizon the estimate"
        " carries its last value forward, so in small or heavily censored"
        " deciles the observed column is softer than its three decimals"
        " look.",
        "<tr><th>Decile</th><th>n</th><th>Predicted</th><th>Observed (KM)</th>\n"
        "    <th>Deviation</th></tr>",
        cal_rows,
    )
    body += f"""

{tab_brier}

{fig_cal}

{tab_cal}"""
    doc.section("results", "Results", body)


def _sec_model_uses(c: dict, doc: ReportDoc) -> None:
    shap = c["shap"]
    shap_rows = "\n".join(
        f"<tr><td>{s['feature']}</td><td>{s['mean_abs_shap']:.3f}</td></tr>" for s in shap[:8]
    )
    tab_shap = doc.table(
        "shap-top",
        "Top eight features by mean absolute attribution.",
        "<tr><th>Feature</th><th>Mean |attribution|</th></tr>",
        shap_rows,
    )
    fig_bar = doc.figure(
        "shap-bar",
        img_uri(c["figures_dir"], "shap_bar.png"),
        "Mean absolute SHAP by feature",
        "Mean absolute attribution by feature.",
    )
    fig_bee = doc.figure(
        "beeswarm",
        img_uri(c["figures_dir"], "shap_beeswarm.png"),
        "SHAP beeswarm across the explanation sample",
        "Per-row attributions across the explanation sample. For a yes/no"
        " feature, such as a one-hot category flag, the high (red) end simply"
        " means the row is in that category.",
    )
    fig_dep = doc.figure(
        "dependence",
        img_uri(c["figures_dir"], "shap_dependence.png"),
        "SHAP dependence plots",
        "Attribution against feature value for the strongest numeric"
        " features; category flags carry no shape and stay in the ranking"
        " above. A run short on numeric features fills the grid with flags"
        " instead.",
    )
    body = f"""<p>Feature attributions (SHAP values, for SHapley Additive exPlanations)
are computed on the log scale of survival time; +0.3 multiplies predicted
survival by about 1.35, and negative values shorten it.</p>

<p>Attributions are descriptive. Correlated features split credit by the
model's internal choices as much as by the data, and the values are
in-sample, computed on the final model's own training rows. Directions are
more trustworthy than magnitudes.</p>

<p>Figure @fig:shap-bar ranks features, Table @tab:shap-top lists the top
eight, Figure @fig:beeswarm shows the per-{c["unit"]} spread, and
Figure @fig:dependence traces attribution against value.</p>

{fig_bar}

{tab_shap}

{fig_bee}

{fig_dep}"""
    if c["g"] and c["has_oracle"]:
        body += "\n" + _pk(
            "mechanism-pointer",
            "<p>The run's notes check this ranking against the generator's"
            " installed mechanisms.</p>",
        )
    else:
        body += "\n" + _pk(
            "no-mechanism",
            "<p>On this data there is no known mechanism to check the ranking"
            ' against, so read it as "what this model leaned on", not as'
            " importance in the world.</p>",
        )
    doc.section("model-uses", "What the model uses", body)


def _sec_limitations(c: dict, doc: ReportDoc) -> None:
    parts: list[str] = []
    if c["g"]:
        parts.append(
            _pk(
                "generator-limits",
                """<p><strong>The generator encodes a prior, not evidence,</strong> so
the concordance here is an upper bound on production performance.
Lifetimes are drawn and resampled independently, understating real-book
uncertainty, and administrative retirement is modeled as independent
censoring, with competing risks left as future work.</p>""",
            )
        )
    losing = [h for h, v in c["brier"].items() if v["xgb"] >= v["km_marginal"]]
    if losing:
        losing_text = ", ".join(h.removesuffix(c["tua"]) + f" {c['tu']}" for h in losing)
        parts.append(
            _pk(
                "losing-horizons",
                f"""<p><strong>Absolute probabilities are not usable at
{losing_text}.</strong> The model loses to the no-skill forecast on the
censoring-weighted Brier score there. Ranking and probability quality are
separate, so use this model to order {c["units"]}, not to act on absolute
probabilities at those horizons.</p>""",
            )
        )
    parts.append(f"""<p><strong>Censoring may be informative.</strong> The evaluation assumes
{c["units"]} stop being observed for reasons unrelated to their risk; early
exits of {c["units"]} about to end anyway bias survival estimates
upward.</p>""")
    if c["notes"].get("limitations"):
        parts.append(c["notes"]["limitations"])
    parts.append(f"""<p><strong>Every {c["unit"]} shares one curve shape.</strong> The
predictive scale is a single fitted number, so the model shifts a
{c["unit"]}'s survival curve earlier or later but never reshapes it;
per-{c["unit"]} width is future work.</p>""")
    parts.append(f"""<p><strong>Harrell's concordance is biased under heavy
censoring,</strong> and the final fold is {pct(c["last_fold_censored"], 0)}
censored; read Table @tab:folds with that in mind.</p>""")
    doc.section("limitations", "Limitations", "\n\n".join(parts))


def _sec_repro(c: dict, doc: ReportDoc) -> None:
    body = f"""<p>Python 3.11 or later. From the repository root:</p>

<pre><code>{c["command"]}</code></pre>

<p>Every number is read from the run's
<code>metrics.json</code> at build time, and a figure the prose never cites
fails the build. <code>requirements.txt</code> pins the exact versions the
committed numbers came from.</p>"""
    doc.section("repro", "Reproducing this run", body)


def _sec_addendum(c: dict, doc: ReportDoc) -> None:
    pool = c["pool"]
    km_fig = doc.figure(
        "km",
        img_uri(c["figures_dir"], "km_by_asset_class.png"),
        "Kaplan-Meier survival curves by asset class",
        "Kaplan-Meier survival curves by asset class. The fastest-decaying"
        " class is installed by the generator, and a fitted model should"
        " recover it.",
    )
    body = f"""<p>Effects are installed as fixed shifts on log survival time;
nothing in the generator is proprietary (constants in the run's notes).
Figure @fig:km shows the curves by asset class.</p>

{km_fig}

<h3>@sec:synthetic-truth.1 The oracle ceiling</h3>

<p>The oracle ranking orders strategies by the latent log-time the
generator actually used; nothing is fitted, and the ranking predates the
noise draw. Its {pool["c_oracle"]:.3f} bounds every model; the gap to a
perfect score is installed noise, and models reading only observables sit
somewhat below it. A suite test asserts the model
never outscores it; beating perfect information indicates a leak.</p>

<h3>@sec:synthetic-truth.2 Generator-seed dependence</h3>

{seed_dependence_para(c["m"], c["m8"])}"""
    doc.addendum("synthetic-truth", "Synthetic ground truth", body)


def compose_report(ctx: dict) -> str:
    c = _derive(ctx)
    doc = ReportDoc()
    _sec_summary(c, doc)
    if c["notes"].get("motivation"):
        doc.section("motivation", "Motivation", c["notes"]["motivation"])
    _sec_data(c, doc)
    _sec_method(c, doc)
    _sec_results(c, doc)
    _sec_model_uses(c, doc)
    if c["notes"].get("interpretation"):
        doc.section("interpretation", "Interpretation", c["notes"]["interpretation"])
    _sec_limitations(c, doc)
    _sec_repro(c, doc)
    if c["g"]:
        _sec_addendum(c, doc)
    return doc.render(
        doctype="Technical Report",
        title=ctx["title"],
        subtitle=ctx["subtitle"],
        meta_rows=ctx["meta_rows"],
        footer=ctx["footer"],
    )
